/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package video;

import ProcesosThreads.MonitorServicios;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raven
 */
public class PanelYouTube extends javax.swing.JFrame {

    String urlVideo = "https://www.youtube.com/watch?v=MM0lWsvieaE";
    DefaultListModel l;

    int formAnch, formAlto;
    private int indx_repVideo = 0;

    /**
     * Creates new form Testing
     */
    public PanelYouTube() {
        initComponents();
        player.init(this);
        //ee.init(player.getMediaPlayerFactory(), player.getMediaPlayer(), player.getEqualizer());
        player.prepare(urlVideo);

        formAnch = this.getWidth();
        formAlto = this.getHeight();
        //player.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player = new com.raven.video_player.VideoPlayer();
        panel_listaRep = new javax.swing.JPanel();
        txt_video = new javax.swing.JTextField();
        bt_add = new javax.swing.JButton();
        bt_play = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_videos = new javax.swing.JList<>();
        bt_stop = new javax.swing.JButton();
        bt_quitar = new javax.swing.JButton();
        bt_sig = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bt_actListRep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel_listaRep.setBackground(new java.awt.Color(213, 225, 238));

        bt_add.setText("Agregar");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/play.png"))); // NOI18N
        bt_play.setText("Play");
        bt_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_playActionPerformed(evt);
            }
        });

        list_videos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "https://www.youtube.com/watch?v=MM0lWsvieaE", "https://www.youtube.com/watch?v=ZpsV5SGa5R4", "https://www.youtube.com/watch?v=-RkQDlUV4Fc", "https://www.youtube.com/watch?v=BXu1AUar2VY&ab_channel=TropicalHouseRadio" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_videos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_videosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_videos);

        bt_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/anterior.png"))); // NOI18N
        bt_stop.setText("Stop");
        bt_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stopActionPerformed(evt);
            }
        });

        bt_quitar.setText("Quitar");
        bt_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quitarActionPerformed(evt);
            }
        });

        bt_sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/siguiente.png"))); // NOI18N
        bt_sig.setText("Siguiente");
        bt_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sigActionPerformed(evt);
            }
        });

        jButton2.setText("Pantalla Completa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bt_actListRep.setText("Act List Rep");
        bt_actListRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actListRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_listaRepLayout = new javax.swing.GroupLayout(panel_listaRep);
        panel_listaRep.setLayout(panel_listaRepLayout);
        panel_listaRepLayout.setHorizontalGroup(
            panel_listaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_listaRepLayout.createSequentialGroup()
                .addComponent(txt_video)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_listaRepLayout.createSequentialGroup()
                .addGroup(panel_listaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_listaRepLayout.createSequentialGroup()
                        .addComponent(bt_play, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_listaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_sig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_actListRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel_listaRepLayout.setVerticalGroup(
            panel_listaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_listaRepLayout.createSequentialGroup()
                .addGroup(panel_listaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_video, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_add)
                    .addComponent(bt_quitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_listaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_play)
                    .addComponent(bt_stop)
                    .addComponent(bt_sig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_listaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(bt_actListRep)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(player, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_listaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_listaRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void bt_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_playActionPerformed
        if (bt_play.getText().equals("Play")) {
            if (list_videos.getSelectedIndex() != -1) {
                urlVideo = list_videos.getModel().getElementAt(list_videos.getSelectedIndex());
                player.prepare(urlVideo);
                player.play();
                stdRep = "play";
            } else {
                PLAY();
            }
            bt_play.setText("Pause");
        } else {
            stdRep = "pause";
            player.pause();
            bt_play.setText("Play");
        }
    }//GEN-LAST:event_bt_playActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        l = new DefaultListModel();
        //l = (DefaultListModel) list_videos.getModel();
        //l.addElement(list_videos.getModel());
        //Thread hilo = new Thread((Runnable) this);
        //hilo.start();
        //MonitorServicios mon = new MonitorServicios();
        //Sincronizador
        //mon.reloj();
    }//GEN-LAST:event_formWindowOpened

    private void bt_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stopActionPerformed
        ANTERIOR();
    }//GEN-LAST:event_bt_stopActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        if (!txt_video.getText().equals("")) {
            l.addElement(txt_video.getText());
            list_videos.setModel(l);
            txt_video.setText("");
        }
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quitarActionPerformed
        if (list_videos.getModel().getSize() > 0) {
            System.out.println("" + list_videos.getSelectedIndex());
            if (list_videos.getSelectedIndex() != 1) {
                l.remove(list_videos.getSelectedIndex());
                list_videos.setModel(l);
            } else {
                l.remove(0);
                list_videos.setModel(l);
            }
        }
    }//GEN-LAST:event_bt_quitarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sigActionPerformed
        SIGUIENTE();
    }//GEN-LAST:event_bt_sigActionPerformed

    private void bt_actListRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actListRepActionPerformed
        act_listRep();
    }//GEN-LAST:event_bt_actListRepActionPerformed

    private void list_videosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_videosMouseClicked
        if (list_videos.getModel().getSize() > 0) {
            if (list_videos.getSelectedIndex() != -1) {
                urlVideo = list_videos.getSelectedValue();
                indx_repVideo = list_videos.getSelectedIndex();
                System.out.println("" + urlVideo);
            }
        }
    }//GEN-LAST:event_list_videosMouseClicked

    public void fullScreen(boolean siNo) {
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        int pantAnch = d.width;
        int pantAlto = d.height;
        if (siNo) {
            this.setSize(pantAnch, pantAlto);
            //this.setExtendedState(MAXIMIZED_BOTH);
        } else {

            this.setSize(formAnch, formAlto);
        }
        //this.setLocationByPlatform(true);
    }

    public void ingreso() {
        String consulta = "INSERT INTO AUDIO_CTRL () VALUES ()";
        //Connection conexion = nConexion.conectorMySQL();
        try {
            PreparedStatement ingresoSQL = (PreparedStatement) conectorMySQL().clientPrepareStatement(consulta);
            int resultConsultas = ingresoSQL.executeUpdate();
            if (resultConsultas > 0) {
                JOptionPane.showMessageDialog(null, "Actualizacion Ingresada");
            }
        } catch (SQLException | HeadlessException e) {
            e.printStackTrace();
        }
    }

    private void act_listRep() {
        //l = (DefaultListModel) list_videos.getModel();
        try {
            ResultSet rs = consultaBd("SELECT * FROM AUDIO_CTRL.rep_youtube;");
            list_videos.removeAll();
            l.clear();
            while (rs.next()) {
                l.addElement(rs.getString(2));
            }
            list_videos.setModel(l);
        } catch (SQLException e) {
            System.out.println("Error SQl:\n" + e);
        } catch (Exception e) {
            System.out.println("Error en la conexion:\n" + e);
        }
    }

    String ip = "172.17.0.2";
    String pt = "3306";
    String usr = "admin", pwd = "Dx.1706%";
    Connection con;
    String driverMysql = "com.mysql.jdbc.Connection";

    public ResultSet consultaBd(String consulta) {
        usr = "admin";
        pwd = "Dx.1706%";
        ResultSet rs;
        try {
            con = conectorMySQL();
            Statement st = (Statement) con.createStatement();
            rs = st.executeQuery(consulta);
        } catch (SQLException ex) {
            System.out.println(ex);
            rs = null;
        }
        return rs;
    }

    public com.mysql.jdbc.Connection conectorMySQL() {
        //System.out.println("SO "+sop+" Host: "+hst+" Plataforma: "+ptf+" User: "+usr+" Pasword: "+pwd+" Puerto: "+prt+" Base Datos: "+bd);
        String dir_url_MySql = "jdbc:mysql://" + ip + ":3306/AUDIO_CTRL";
        com.mysql.jdbc.Connection conexionMysql = null;
        //System.out.println(sop);
        try {//cargamos el driver mysql
            Class.forName(driverMysql);
            //creamos un enlace a la bd
            conexionMysql = (com.mysql.jdbc.Connection) DriverManager.getConnection(dir_url_MySql, usr, pwd);
            //conexionMysql.close();
            //System.out.print("Conexion MySQL exitosa");
        } catch (ClassNotFoundException | SQLException e) {
            //ver_error("main.publicarActualizacion.conectorMySQL()",e.getMessage(),e.fillInStackTrace().toString());
        }
        return conexionMysql;
    }

    /**
     * ****CONTROL REMOTO DE ACCIONE****
     */
    public boolean verPanel(boolean verOculta) {
        panel_listaRep.setVisible(verOculta);
        return panel_listaRep.isVisible();
    }

    String stdRep = "stop";

    public boolean PLAY() {
        if (stdRep.equals("stop")) {
            if (list_videos.getModel().getSize() > 0) {
                urlVideo = list_videos.getModel().getElementAt(indx_repVideo);
                player.prepare(urlVideo);
                player.play();
            } else {
                urlVideo = "https://www.youtube.com/watch?v=MM0lWsvieaE";
                player.prepare(urlVideo);
                player.play();
            }
            bt_play.setText("Play");
        }else if (stdRep.equals("pausa")) {
            player.play();
        }

        System.out.println("" + urlVideo);
        return true;
    }

    public boolean STOP() {
        player.prepare(urlVideo);
        player.pause();
        bt_play.setText("Play");
        return true;
    }

    public boolean PAUSE(boolean pause) {
        player.pause();
        bt_play.setText("Pause");
        return true;
    }

    public void SIGUIENTE() {
        if (indx_repVideo < list_videos.getModel().getSize()) {
//            System.out.println("IDX cont: "+indx_repVideo+" IDX Lista "+list_videos.getModel().getSize());
            indx_repVideo++;
            urlVideo = list_videos.getModel().getElementAt(indx_repVideo);
            System.out.println(urlVideo);
            PLAY();
        }
    }

    public void ANTERIOR() {
        if (indx_repVideo > 0) {
            System.out.println("IDX cont: "+indx_repVideo+" IDX Lista "+list_videos.getModel().getSize());            
            indx_repVideo--;
            urlVideo = list_videos.getModel().getElementAt(indx_repVideo);
            System.out.println(urlVideo);
            PLAY();
        }
    }

    public void ACT_LISTA() {
        act_listRep();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelYouTube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelYouTube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelYouTube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelYouTube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelYouTube().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actListRep;
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_play;
    private javax.swing.JButton bt_quitar;
    private javax.swing.JButton bt_sig;
    private javax.swing.JButton bt_stop;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list_videos;
    private javax.swing.JPanel panel_listaRep;
    private com.raven.video_player.VideoPlayer player;
    private javax.swing.JTextField txt_video;
    // End of variables declaration//GEN-END:variables
}
